export const roseTocItems = [
  { id: "rose-drawing-tutorial-information", label: "Rose Drawing Tutorial Information" },
  { id: "materials-you-need", label: "Materials You Need" },
  { id: "rose-drawing-step-by-step", label: "Rose Drawing Step by Step" },
  { id: "simple-rose-drawing-tips-for-beginners", label: "Simple Rose Drawing Tips for Beginners" },
  { id: "how-to-create-outline", label: "How to Create Outline" },
  { id: "basic-outline", label: "Basic Outline", level: 3 as const },
  { id: "detailed-outline", label: "Detailed Outline", level: 3 as const },
  { id: "how-to-make-a-realistic-rose-drawing", label: "How to Make a Realistic Rose Drawing" },
  { id: "petal-direction", label: "Petal Direction", level: 3 as const },
  { id: "overlapping-forms", label: "Overlapping Forms", level: 3 as const },
  { id: "folded-edges", label: "Folded Edges", level: 3 as const },
  { id: "light-and-shadow", label: "Light and Shadow", level: 3 as const },
  { id: "uneven-shapes", label: "Uneven Shapes", level: 3 as const },
  {
    id: "red-rose-drawing-with-colored-pencils",
    label: "Red Rose Drawing with Colored Pencils",
  },
  { id: "white-rose-drawing-tips", label: "White Rose Drawing Tips" },
  { id: "small-rose-drawing-practice", label: "Small Rose Drawing Practice" },
  { id: "cute-rose-drawing-easy-idea", label: "Cute Rose Drawing Easy Idea" },
  { id: "rose-bouquet-drawing-basics", label: "Rose Bouquet Drawing Basics" },
  { id: "common-mistakes-when-drawing-a-rose", label: "Common Mistakes When Drawing a Rose" },
  { id: "making-every-petal-the-same", label: "Making Every Petal the Same", level: 3 as const },
  { id: "starting-with-dark-lines", label: "Starting with Dark Lines", level: 3 as const },
  { id: "making-the-center-too-large", label: "Making the Center Too Large", level: 3 as const },
  { id: "adding-too-many-random-lines", label: "Adding Too Many Random Lines", level: 3 as const },
  { id: "forgetting-the-base-of-the-flower", label: "Forgetting the Base of the Flower", level: 3 as const },
  { id: "shading-every-area-equally", label: "Shading Every Area Equally", level: 3 as const },
  { id: "worksheets", label: "Downloadable Worksheet" },
  { id: "faq", label: "Frequently Asked Questions" },
  { id: "start-your-roses-drawing", label: "Start Your Roses Drawing" },
] as const;
