export const sunflowerTocItems = [
  { id: "sunflower-anatomy-at-a-glance", label: "Sunflower Anatomy at a Glance" },
  { id: "tutorial-overview", label: "Tutorial Overview" },
  { id: "materials-for-your-sunflower-sketch", label: "Materials for Your Sunflower Sketch" },
  { id: "build-the-flower-with-basic-shapes", label: "Build the Flower with Basic Shapes" },
  { id: "sunflower-drawing-step-by-step", label: "Sunflower Drawing Step by Step" },
  { id: "how-to-draw-sunflower-seeds", label: "How to Draw Sunflower Seeds" },
  { id: "basic-seed-texture", label: "Basic Seed Texture", level: 3 as const },
  { id: "intermediate-seed-pattern", label: "Intermediate Seed Pattern", level: 3 as const },
  { id: "detailed-seed-pattern", label: "Detailed Seed Pattern", level: 3 as const },
  { id: "sunflower-pencil-drawing-techniques", label: "Sunflower Pencil Drawing Techniques" },
  { id: "create-a-clean-sunflower-outline-drawing", label: "Create a Clean Sunflower Outline Drawing" },
  { id: "how-to-make-a-realistic-sunflower-drawing", label: "How to Make a Realistic Sunflower Drawing" },
  { id: "vary-the-petals", label: "Vary the Petals", level: 3 as const },
  { id: "build-the-center-gradually", label: "Build the Center Gradually", level: 3 as const },
  { id: "show-the-flowers-weight", label: "Show the Flower’s Weight", level: 3 as const },
  { id: "add-leaf-texture", label: "Add Leaf Texture", level: 3 as const },
  { id: "control-the-shadows", label: "Control the Shadows", level: 3 as const },
  { id: "easy-sunflower-drawing-for-kids", label: "Easy Sunflower Drawing for Kids" },
  { id: "small-sunflower-drawing-practice", label: "Small Sunflower Drawing Practice" },
  { id: "coloring-a-beautiful-sunflower-drawing", label: "Coloring a Beautiful Sunflower Drawing" },
  { id: "common-mistakes", label: "Common Mistakes" },
  { id: "making-the-center-too-small", label: "Making the Center Too Small", level: 3 as const },
  { id: "drawing-identical-petals", label: "Drawing Identical Petals", level: 3 as const },
  { id: "placing-seeds-randomly", label: "Placing Seeds Randomly", level: 3 as const },
  { id: "making-the-stem-too-thin", label: "Making the Stem Too Thin", level: 3 as const },
  { id: "forgetting-overlapping-petals", label: "Forgetting Overlapping Petals", level: 3 as const },
  { id: "shading-every-petal-equally", label: "Shading Every Petal Equally", level: 3 as const },
  { id: "using-smooth-leaf-edges", label: "Using Smooth Leaf Edges", level: 3 as const },
  { id: "worksheets", label: "Downloadable Worksheet" },
  { id: "faq", label: "Frequently Asked Questions" },
  { id: "complete-your-drawing", label: "Complete Your Drawing" },
] as const;
