export const tulipTocItems = [
  { id: "why-drawing-tulips-are-beginner-friendly", label: "Why Drawing Tulips Are Beginner-Friendly" },
  { id: "quick-drawing-plan", label: "Quick Drawing Plan" },
  { id: "materials-you-will-need", label: "Materials You Will Need" },
  { id: "understand-the-tulip-shape-first", label: "Understand the Tulip Shape First" },
  { id: "tulip-drawing-step-by-step", label: "Tulip Drawing Step by Step" },
  { id: "create-a-clean-tulip-outline-drawing", label: "Create a Clean Tulip Outline Drawing" },
  { id: "tulip-line-drawing-tips", label: "Tulip Line Drawing Tips" },
  { id: "tulip-pencil-drawing-and-shading", label: "Tulip Pencil Drawing and Shading" },
  { id: "how-to-make-a-realistic-tulip-drawing", label: "How to Make a Realistic Tulip Drawing" },
  { id: "vary-the-petal-heights", label: "Vary the Petal Heights", level: 3 as const },
  { id: "show-clear-overlap", label: "Show Clear Overlap", level: 3 as const },
  { id: "keep-the-bloom-rounded", label: "Keep the Bloom Rounded", level: 3 as const },
  { id: "use-gentle-petal-texture", label: "Use Gentle Petal Texture", level: 3 as const },
  { id: "shape-the-leaves-naturally", label: "Shape the Leaves Naturally", level: 3 as const },
  { id: "pink-tulip-drawing", label: "Pink Tulip Drawing" },
  { id: "easy-tulip-drawing-for-kids", label: "Easy Tulip Drawing for Kids" },
  { id: "drawing-a-tulip-bouquet", label: "Drawing a Tulip Bouquet" },
  { id: "common-mistakes", label: "Common Mistakes" },
  { id: "making-the-bloom-completely-round", label: "Making the Bloom Completely Round", level: 3 as const },
  { id: "drawing-too-many-visible-petals", label: "Drawing Too Many Visible Petals", level: 3 as const },
  { id: "making-every-petal-the-same-height", label: "Making Every Petal the Same Height", level: 3 as const },
  { id: "using-a-very-thin-stem", label: "Using a Very Thin Stem", level: 3 as const },
  { id: "drawing-short-round-leaves", label: "Drawing Short, Round Leaves", level: 3 as const },
  { id: "adding-heavy-shading-too-early", label: "Adding Heavy Shading Too Early", level: 3 as const },
  { id: "leaving-construction-lines-visible", label: "Leaving Construction Lines Visible", level: 3 as const },
  { id: "worksheets", label: "Downloadable Worksheet" },
  { id: "faq", label: "Frequently Asked Questions" },
  { id: "complete-your-tulip-drawing", label: "Complete Your Tulip Drawing" },
] as const;
